# Generated by Django 4.1 on 2022-08-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossoutOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crossout', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=50)),
            ],
        ),
    ]
